### ISSUE TITLE
Define benchmark and module YAML semantics (i.e. parameters)

### ISSUE THREAD

**Issue by imallona** [omnibenchmark/omni_workflow#2]

**Comment by imallona** [comment]
I'm recycling the "state machine-based YAML" at https://github.com/omnibenchmark/internal_docs/blob/master/architecture/snakemake_design.md , perhaps we could edit/build on that.

**Comment by almutlue** [comment]
__RE test dataset specification__: What about adding a test flag/field to at least one module per stage in the benchmark definition file. In that case test datasets will be part of the benchmark, but I think that would be fine?
